import esbuild from "esbuild";
import process from "process";

const production =
    process.argv[2] === "production";


const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/`;


const buildOptions = {

    entryPoints: [
        "src/main.ts"
    ],

    bundle: true,

    external: [
        "obsidian"
    ],

    format: "cjs",

    target: "es2018",

    logLevel: "info",

    sourcemap:
        production
            ? false
            : "inline",

    treeShaking: true,

    outfile: "main.js",

    banner: {
        js: banner
    }

};


if (production) {

    esbuild.buildSync(
        buildOptions
    );

}
else {

    esbuild.context(
        buildOptions
    ).then(
        ctx => ctx.watch()
    );

}