/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CalloutMetadataPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/parser.ts
var STYLE_TOKENS = /* @__PURE__ */ new Set([
  "shadow",
  "rounded",
  "outline",
  "glass",
  "gradient",
  "borderless",
  "compact",
  "hover",
  "sticky"
]);
function parseMetadata(raw) {
  const result = {};
  const tokens = raw.split("|").map((token) => token.trim()).filter(Boolean);
  for (const token of tokens) {
    if (token.includes("=")) {
      const separator = token.indexOf("=");
      const key = token.slice(0, separator).toLowerCase();
      const value = token.slice(separator + 1).trim();
      if (key === "css" && value) {
        result.css = result.css ? `${result.css} ${value}` : value;
      }
      continue;
    }
    if (/^\d+$/.test(token)) {
      const width = Number(token);
      result.width = Math.min(
        100,
        Math.max(
          0,
          width
        )
      );
      continue;
    }
    const lower = token.toLowerCase();
    if (lower === "left" || lower === "center" || lower === "right") {
      result.align = lower;
      continue;
    }
    if (STYLE_TOKENS.has(
      lower
    )) {
      result[lower] = true;
      continue;
    }
    result.color = token;
  }
  return result;
}

// src/utils.ts
var _ctx;
function getContext() {
  if (_ctx === void 0) {
    const c = document.createElement("canvas");
    c.width = 1;
    c.height = 1;
    _ctx = c.getContext("2d");
  }
  return _ctx;
}
function parseHex(hex) {
  const m = hex.match(/^#([0-9a-f]{3,8})$/i);
  if (!m)
    return null;
  let h = m[1];
  if (h.length === 3)
    h = h[0] + h[0] + h[1] + h[1] + h[2] + h[2];
  if (h.length !== 6 && h.length !== 8)
    return null;
  return `${parseInt(h.slice(0, 2), 16)}, ${parseInt(h.slice(2, 4), 16)}, ${parseInt(h.slice(4, 6), 16)}`;
}
function resolveColor(input) {
  if (!input)
    return null;
  if (/^\d{1,3}\s*,\s*\d{1,3}\s*,\s*\d{1,3}$/.test(input)) {
    return input;
  }
  if (input.startsWith("#")) {
    return parseHex(input);
  }
  const ctx = getContext();
  if (!ctx)
    return null;
  const sentinel = "#010203";
  ctx.fillStyle = sentinel;
  ctx.fillStyle = input;
  if (ctx.fillStyle === sentinel && input.toLowerCase() !== sentinel) {
    return null;
  }
  const resolved = ctx.fillStyle;
  if (resolved.startsWith("#")) {
    return parseHex(resolved);
  }
  const m = resolved.match(/rgba?\(\s*(\d+),\s*(\d+),\s*(\d+)/);
  return m ? `${m[1]}, ${m[2]}, ${m[3]}` : null;
}

// src/processor.ts
var PROCESSED = "data-cm-processed";
var STYLE_FLAGS = [
  "shadow",
  "rounded",
  "outline",
  "glass",
  "gradient",
  "borderless",
  "compact",
  "hover",
  "sticky"
];
function processCallouts(container) {
  const callouts = container.querySelectorAll(
    `.callout[data-callout-metadata]:not([${PROCESSED}])`
  );
  callouts.forEach((el) => {
    el.setAttribute(
      PROCESSED,
      ""
    );
    const raw = el.getAttribute(
      "data-callout-metadata"
    );
    if (!raw) {
      return;
    }
    applyMetadata(
      el,
      parseMetadata(raw)
    );
  });
}
function applyMetadata(el, meta) {
  const wrapper = el.closest(
    ".cm-embed-block"
  );
  if (meta.width != null) {
    el.dataset.width = String(meta.width);
    el.style.setProperty(
      "--cm-callout-width",
      `${meta.width}%`
    );
    if (wrapper) {
      wrapper.style.setProperty(
        "--cm-callout-width",
        `${meta.width}%`
      );
    }
  }
  if (meta.color) {
    const rgb = resolveColor(
      meta.color
    );
    if (rgb) {
      el.style.setProperty(
        "--callout-color",
        rgb
      );
    }
    el.dataset.color = meta.color;
  }
  if (meta.align) {
    el.dataset.align = meta.align;
    if (wrapper) {
      wrapper.dataset.align = meta.align;
    }
  }
  STYLE_FLAGS.forEach(
    (flag) => {
      if (meta[flag]) {
        el.dataset[flag] = "";
      }
    }
  );
  if (meta.css) {
    meta.css.split(/\s+/).filter(Boolean).forEach(
      (cls) => {
        el.classList.add(
          cls
        );
      }
    );
    el.dataset.css = meta.css;
  }
}

// src/settings.ts
var import_obsidian = require("obsidian");

// src/constants.ts
var SUPPORT_LINKS = [
  {
    text: "\u2615 Buy Me a Coffee",
    href: "https://buymeacoffee.com/erinskidds",
    cls: "coffee-link"
  },
  {
    text: "\u2B50 Star on GitHub",
    href: "https://github.com/DudeThatsErin/CalloutMetadata",
    cls: "github-link"
  },
  {
    text: "\u{1F41B} Report Issues",
    href: "https://github.com/DudeThatsErin/CalloutMetadata/issues",
    cls: "issues-link"
  },
  {
    text: "\u{1F4AC} Discord Support",
    href: "https://discord.gg/XcJWhE3SEA",
    cls: "discord-link"
  }
];

// src/settings.ts
var CalloutMetadataSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  getSettingDefinitions() {
    const self = this;
    const s = () => self.plugin.settings;
    return [
      {
        type: "group",
        heading: "Support & Links",
        items: [{
          name: "Support & links",
          searchable: false,
          render: (setting) => {
            setting.nameEl.remove();
            setting.descEl.remove();
            setting.controlEl.style.cssText = "display:flex;flex-wrap:wrap;gap:8px;padding:4px 0;justify-content:flex-start;width:100%";
            SUPPORT_LINKS.forEach(({ text, href, cls }) => {
              const a = setting.controlEl.createEl("a", { text, href });
              a.className = `support-link ${cls}`;
              a.target = "_blank";
              a.rel = "noopener noreferrer";
            });
          }
        }]
      },
      {
        type: "group",
        heading: "Rounded Corners",
        items: [
          {
            name: "Border Radius",
            desc: "Corner radius for callouts using the rounded token.",
            aliases: ["rounded", "corners", "border radius"],
            render: (setting) => {
              setting.addSlider((slider) => {
                slider.setLimits(0, 32, 1).setValue(s().roundedRadius).setDynamicTooltip().onChange(async (value) => {
                  self.plugin.settings.roundedRadius = value;
                  await self.plugin.saveSettings();
                });
              });
            }
          }
        ]
      },
      {
        type: "group",
        heading: "Shadow",
        items: [
          {
            name: "Shadow Spread",
            desc: "Box-shadow offset and blur for callouts using the shadow token.",
            aliases: ["shadow strength", "box shadow", "shadow size"],
            render: (setting) => {
              setting.addText((text) => {
                text.setPlaceholder("0 2px 8px").setValue(s().shadowStrength).onChange(async (value) => {
                  self.plugin.settings.shadowStrength = value;
                  await self.plugin.saveSettings();
                });
              });
            }
          },
          {
            name: "Shadow Color (Light Mode)",
            desc: "Shadow color when using the light theme.",
            aliases: ["shadow color light", "light shadow"],
            render: (setting) => {
              setting.addColorPicker((picker) => {
                picker.setValue(s().shadowColorLight).onChange(async (value) => {
                  self.plugin.settings.shadowColorLight = value;
                  await self.plugin.saveSettings();
                });
              });
            }
          },
          {
            name: "Shadow Color (Dark Mode)",
            desc: "Shadow color when using the dark theme.",
            aliases: ["shadow color dark", "dark shadow"],
            render: (setting) => {
              setting.addColorPicker((picker) => {
                picker.setValue(s().shadowColorDark).onChange(async (value) => {
                  self.plugin.settings.shadowColorDark = value;
                  await self.plugin.saveSettings();
                });
              });
            }
          }
        ]
      },
      {
        type: "group",
        heading: "Outline",
        items: [
          {
            name: "Outline Width",
            desc: "Border thickness for callouts using the outline token.",
            aliases: ["outline size", "border width", "outline thickness"],
            render: (setting) => {
              setting.addSlider((slider) => {
                slider.setLimits(1, 6, 1).setValue(s().outlineWidth).setDynamicTooltip().onChange(async (value) => {
                  self.plugin.settings.outlineWidth = value;
                  await self.plugin.saveSettings();
                });
              });
            }
          },
          {
            name: "Outline Style",
            desc: "Border style for callouts using the outline token.",
            aliases: ["outline dashed", "outline dotted", "border style"],
            render: (setting) => {
              setting.addDropdown((dropdown) => {
                dropdown.addOption("solid", "Solid").addOption("dashed", "Dashed").addOption("dotted", "Dotted").setValue(s().outlineStyle).onChange(async (value) => {
                  self.plugin.settings.outlineStyle = value;
                  await self.plugin.saveSettings();
                });
              });
            }
          },
          {
            name: "Outline Color (Light Mode)",
            desc: "Outline border color when using the light theme.",
            aliases: ["outline color light", "light outline", "border color light"],
            render: (setting) => {
              setting.addColorPicker((picker) => {
                picker.setValue(s().outlineColorLight).onChange(async (value) => {
                  self.plugin.settings.outlineColorLight = value;
                  await self.plugin.saveSettings();
                });
              });
            }
          },
          {
            name: "Outline Color (Dark Mode)",
            desc: "Outline border color when using the dark theme.",
            aliases: ["outline color dark", "dark outline", "border color dark"],
            render: (setting) => {
              setting.addColorPicker((picker) => {
                picker.setValue(s().outlineColorDark).onChange(async (value) => {
                  self.plugin.settings.outlineColorDark = value;
                  await self.plugin.saveSettings();
                });
              });
            }
          }
        ]
      },
      {
        type: "group",
        heading: "Effects",
        items: [
          {
            name: "Glass",
            desc: "Enable the glass effect token for callouts.",
            aliases: ["glass effect", "blur", "frosted", "transparent"],
            render: (setting) => {
              setting.addToggle((toggle) => {
                toggle.setValue(s().enableGlass).onChange(async (value) => {
                  self.plugin.settings.enableGlass = value;
                  await self.plugin.saveSettings();
                });
              });
            }
          },
          {
            name: "Gradient",
            desc: "Enable the gradient effect token for callouts.",
            aliases: ["gradient effect", "gradient background"],
            render: (setting) => {
              setting.addToggle((toggle) => {
                toggle.setValue(s().enableGradient).onChange(async (value) => {
                  self.plugin.settings.enableGradient = value;
                  await self.plugin.saveSettings();
                });
              });
            }
          },
          {
            name: "Compact",
            desc: "Enable the compact token to reduce callout padding.",
            aliases: ["compact mode", "small padding", "tight"],
            render: (setting) => {
              setting.addToggle((toggle) => {
                toggle.setValue(s().enableCompact).onChange(async (value) => {
                  self.plugin.settings.enableCompact = value;
                  await self.plugin.saveSettings();
                });
              });
            }
          },
          {
            name: "Hover",
            desc: "Enable the hover animation token for callouts.",
            aliases: ["hover effect", "hover animation", "lift"],
            render: (setting) => {
              setting.addToggle((toggle) => {
                toggle.setValue(s().enableHover).onChange(async (value) => {
                  self.plugin.settings.enableHover = value;
                  await self.plugin.saveSettings();
                });
              });
            }
          },
          {
            name: "Sticky",
            desc: "Enable the sticky positioning token for callouts.",
            aliases: ["sticky position", "pinned", "fixed"],
            render: (setting) => {
              setting.addToggle((toggle) => {
                toggle.setValue(s().enableSticky).onChange(async (value) => {
                  self.plugin.settings.enableSticky = value;
                  await self.plugin.saveSettings();
                });
              });
            }
          }
        ]
      }
    ];
  }
};

// src/types.ts
var DEFAULT_SETTINGS = {
  roundedRadius: 12,
  shadowStrength: "0 2px 8px",
  shadowColorLight: "#00000026",
  shadowColorDark: "#00000040",
  outlineWidth: 2,
  outlineColorLight: "#888888",
  outlineColorDark: "#aaaaaa",
  outlineStyle: "solid",
  enableGlass: true,
  enableGradient: true,
  enableCompact: true,
  enableHover: true,
  enableSticky: true,
  showSupportLinks: true
};

// src/main.ts
var CalloutMetadataPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.settings = {
      ...DEFAULT_SETTINGS
    };
    this.debouncedProcess = (0, import_obsidian2.debounce)(
      () => this.processAllViews(),
      200,
      true
    );
  }
  async onload() {
    await this.loadSettings();
    this.applyCSSVariables();
    this.applyEffectClasses();
    this.registerMarkdownPostProcessor(
      (el) => {
        processCallouts(el);
      }
    );
    this.app.workspace.onLayoutReady(
      () => {
        this.processAllViews();
        this.applyCSSVariables();
        this.applyEffectClasses();
        this.app.workspace.trigger(
          "css-change"
        );
      }
    );
    this.registerEvent(
      this.app.workspace.on(
        "layout-change",
        () => {
          this.debouncedProcess();
        }
      )
    );
    this.registerEvent(
      this.app.workspace.on(
        "css-change",
        () => {
          this.applyCSSVariables();
          this.applyEffectClasses();
        }
      )
    );
    this.addSettingTab(
      new CalloutMetadataSettingTab(
        this.app,
        this
      )
    );
  }
  /**
   * Get the correct document instance.
   *
   * Supports Obsidian popout windows.
   */
  getDocument() {
    return this.app.workspace.containerEl.ownerDocument;
  }
  /**
   * Apply CSS variables from settings.
   */
  applyCSSVariables() {
    const doc = this.getDocument();
    const root = doc.documentElement;
    const body = doc.body;
    const dark = body.classList.contains(
      "theme-dark"
    );
    root.style.setProperty(
      "--cm-rounded-radius",
      `${this.settings.roundedRadius}px`
    );
    root.style.setProperty(
      "--cm-shadow-strength",
      this.settings.shadowStrength
    );
    root.style.setProperty(
      "--cm-shadow-color",
      dark ? this.settings.shadowColorDark : this.settings.shadowColorLight
    );
    root.style.setProperty(
      "--cm-outline-width",
      `${this.settings.outlineWidth}px`
    );
    root.style.setProperty(
      "--cm-outline-color",
      dark ? this.settings.outlineColorDark : this.settings.outlineColorLight
    );
    body.classList.remove(
      "cm-outline-solid",
      "cm-outline-dashed",
      "cm-outline-dotted"
    );
    body.classList.add(
      `cm-outline-${this.settings.outlineStyle}`
    );
  }
  /**
   * Enable/disable optional effects
   * through body classes.
   */
  applyEffectClasses() {
    const doc = this.getDocument();
    const body = doc.body;
    const effects = {
      glass: this.settings.enableGlass,
      gradient: this.settings.enableGradient,
      compact: this.settings.enableCompact,
      hover: this.settings.enableHover,
      sticky: this.settings.enableSticky
    };
    Object.keys(effects).forEach(
      (name) => {
        body.toggleClass(
          `cm-${name}-disabled`,
          !effects[name]
        );
      }
    );
  }
  processAllViews() {
    this.app.workspace.iterateAllLeaves(
      (leaf) => {
        if (leaf.view instanceof import_obsidian2.MarkdownView) {
          processCallouts(
            leaf.view.containerEl
          );
        }
      }
    );
  }
  async loadSettings() {
    const data = await this.loadData();
    const savedSettings = typeof data === "object" && data !== null ? data : {};
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      savedSettings
    );
  }
  async saveSettings() {
    await this.saveData(
      this.settings
    );
    this.applyCSSVariables();
    this.applyEffectClasses();
    this.app.workspace.trigger(
      "css-change"
    );
  }
};
