/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CalloutMetadataPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/parser.ts
var STYLE_TOKENS = /* @__PURE__ */ new Set([
  "shadow",
  "rounded",
  "outline",
  "glass",
  "gradient",
  "borderless",
  "compact",
  "hover",
  "sticky"
]);
function parseMetadata(raw) {
  const result = {};
  const tokens = raw.split("|").map((token) => token.trim()).filter(Boolean);
  for (const token of tokens) {
    if (token.includes("=")) {
      const separator = token.indexOf("=");
      const key = token.slice(0, separator).toLowerCase();
      const value = token.slice(separator + 1).trim();
      if (key === "css" && value) {
        result.css = result.css ? `${result.css} ${value}` : value;
      }
      continue;
    }
    if (/^\d+$/.test(token)) {
      const width = Number(token);
      result.width = Math.min(
        100,
        Math.max(
          0,
          width
        )
      );
      continue;
    }
    const lower = token.toLowerCase();
    if (lower === "left" || lower === "center" || lower === "right") {
      result.align = lower;
      continue;
    }
    if (STYLE_TOKENS.has(
      lower
    )) {
      result[lower] = true;
      continue;
    }
    result.color = token;
  }
  return result;
}

// src/utils.ts
var _ctx;
function getContext() {
  if (_ctx === void 0) {
    const c = document.createElement("canvas");
    c.width = 1;
    c.height = 1;
    _ctx = c.getContext("2d");
  }
  return _ctx;
}
function parseHex(hex) {
  const m = hex.match(/^#([0-9a-f]{3,8})$/i);
  if (!m)
    return null;
  let h = m[1];
  if (h.length === 3)
    h = h[0] + h[0] + h[1] + h[1] + h[2] + h[2];
  if (h.length !== 6 && h.length !== 8)
    return null;
  return `${parseInt(h.slice(0, 2), 16)}, ${parseInt(h.slice(2, 4), 16)}, ${parseInt(h.slice(4, 6), 16)}`;
}
function resolveColor(input) {
  if (!input)
    return null;
  if (/^\d{1,3}\s*,\s*\d{1,3}\s*,\s*\d{1,3}$/.test(input)) {
    return input;
  }
  if (input.startsWith("#")) {
    return parseHex(input);
  }
  const ctx = getContext();
  if (!ctx)
    return null;
  const sentinel = "#010203";
  ctx.fillStyle = sentinel;
  ctx.fillStyle = input;
  if (ctx.fillStyle === sentinel && input.toLowerCase() !== sentinel) {
    return null;
  }
  const resolved = ctx.fillStyle;
  if (resolved.startsWith("#")) {
    return parseHex(resolved);
  }
  const m = resolved.match(/rgba?\(\s*(\d+),\s*(\d+),\s*(\d+)/);
  return m ? `${m[1]}, ${m[2]}, ${m[3]}` : null;
}

// src/processor.ts
var PROCESSED = "data-cm-processed";
var STYLE_FLAGS = [
  "shadow",
  "rounded",
  "outline",
  "glass",
  "gradient",
  "borderless",
  "compact",
  "hover",
  "sticky"
];
function processCallouts(container) {
  const callouts = container.querySelectorAll(
    `.callout[data-callout-metadata]:not([${PROCESSED}])`
  );
  callouts.forEach((el) => {
    el.setAttribute(
      PROCESSED,
      ""
    );
    const raw = el.getAttribute(
      "data-callout-metadata"
    );
    if (!raw) {
      return;
    }
    applyMetadata(
      el,
      parseMetadata(raw)
    );
  });
}
function applyMetadata(el, meta) {
  const wrapper = el.closest(
    ".cm-embed-block"
  );
  if (meta.width != null) {
    el.dataset.width = String(meta.width);
    el.style.setProperty(
      "--cm-callout-width",
      `${meta.width}%`
    );
    if (wrapper instanceof HTMLElement) {
      wrapper.style.setProperty(
        "--cm-callout-width",
        `${meta.width}%`
      );
    }
  }
  if (meta.color) {
    const rgb = resolveColor(
      meta.color
    );
    if (rgb) {
      el.style.setProperty(
        "--callout-color",
        rgb
      );
    }
    el.dataset.color = meta.color;
  }
  if (meta.align) {
    el.dataset.align = meta.align;
    if (wrapper instanceof HTMLElement) {
      wrapper.dataset.align = meta.align;
    }
  }
  STYLE_FLAGS.forEach(
    (flag) => {
      if (meta[flag]) {
        el.dataset[flag] = "";
      }
    }
  );
  if (meta.css) {
    meta.css.split(/\s+/).filter(Boolean).forEach(
      (cls) => {
        el.classList.add(
          cls
        );
      }
    );
    el.dataset.css = meta.css;
  }
}

// src/settings.ts
var import_obsidian = require("obsidian");

// src/constants.ts
var SUPPORT_LINKS = [
  {
    text: "\u2615 Buy Me a Coffee",
    href: "https://buymeacoffee.com/erinskidds",
    cls: "coffee-link"
  },
  {
    text: "\u2B50 Star on GitHub",
    href: "https://github.com/DudeThatsErin/CalloutMetadata",
    cls: "github-link"
  },
  {
    text: "\u{1F41B} Report Issues",
    href: "https://github.com/DudeThatsErin/CalloutMetadata/issues",
    cls: "issues-link"
  },
  {
    text: "\u{1F4AC} Discord Support",
    href: "https://discord.gg/XcJWhE3SEA",
    cls: "discord-link"
  }
];

// src/settings.ts
var CalloutMetadataSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const {
      containerEl
    } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Callout Metadata").setHeading();
    this.renderSupport(containerEl);
    this.renderAppearance(containerEl);
  }
  async updateSettings(callback) {
    callback();
    await this.plugin.saveSettings();
  }
  renderSupport(container) {
    new import_obsidian.Setting(container).setName("Support & Links").setDesc(
      "Support development, report bugs, or get help."
    );
    const wrapper = container.createDiv({
      cls: "support-container"
    });
    SUPPORT_LINKS.forEach((link) => {
      const anchor = wrapper.createEl(
        "a",
        {
          text: link.text,
          href: link.href
        }
      );
      anchor.classList.add(
        "support-link",
        link.cls
      );
      anchor.target = "_blank";
      anchor.rel = "noopener noreferrer";
    });
  }
  renderAppearance(container) {
    new import_obsidian.Setting(container).setName("Appearance").setHeading();
    new import_obsidian.Setting(container).setDesc(
      "These settings customize callouts that use the matching metadata tokens. They do not change every callout in your vault. For example, Border Radius only affects callouts using |rounded, shadows only affect callouts using |shadow, and outlines only affect callouts using |outline."
    );
    new import_obsidian.Setting(container).setName("Border Radius").setDesc(
      "Sets the corner radius for callouts using the 'rounded' token (example: [!note|rounded])."
    ).addSlider((slider) => {
      slider.setLimits(
        0,
        32,
        1
      ).setValue(
        this.plugin.settings.roundedRadius
      ).onChange(async (value) => {
        await this.updateSettings(
          () => {
            this.plugin.settings.roundedRadius = value;
          }
        );
      });
    });
    new import_obsidian.Setting(container).setName("Shadow Strength").setDesc(
      "Sets the box-shadow values for callouts using the 'shadow' token (example: [!note|shadow])."
    ).addText((text) => {
      text.setValue(
        this.plugin.settings.shadowStrength
      ).onChange(async (value) => {
        await this.updateSettings(
          () => {
            this.plugin.settings.shadowStrength = value;
          }
        );
      });
    });
    new import_obsidian.Setting(container).setName("Shadow Color (Light)").setDesc(
      "Sets the shadow color for 'shadow' callouts while using the light theme."
    ).addColorPicker((picker) => {
      picker.setValue(
        this.plugin.settings.shadowColorLight
      ).onChange(async (value) => {
        await this.updateSettings(
          () => {
            this.plugin.settings.shadowColorLight = value;
          }
        );
      });
    });
    new import_obsidian.Setting(container).setName("Shadow Color (Dark)").setDesc(
      "Sets the shadow color for 'shadow' callouts while using the dark theme."
    ).addColorPicker((picker) => {
      picker.setValue(
        this.plugin.settings.shadowColorDark
      ).onChange(async (value) => {
        await this.updateSettings(
          () => {
            this.plugin.settings.shadowColorDark = value;
          }
        );
      });
    });
    new import_obsidian.Setting(container).setName("Outline Width").setDesc(
      "Sets the border thickness for callouts using the 'outline' token (example: [!warning|outline])."
    ).addSlider((slider) => {
      slider.setLimits(
        1,
        6,
        1
      ).setValue(
        this.plugin.settings.outlineWidth
      ).onChange(async (value) => {
        await this.updateSettings(
          () => {
            this.plugin.settings.outlineWidth = value;
          }
        );
      });
    });
    new import_obsidian.Setting(container).setName("Outline Style").setDesc(
      "Sets the border style for callouts using the 'outline' token."
    ).addDropdown((dropdown) => {
      dropdown.addOption(
        "solid",
        "Solid"
      ).addOption(
        "dashed",
        "Dashed"
      ).addOption(
        "dotted",
        "Dotted"
      ).setValue(
        this.plugin.settings.outlineStyle
      ).onChange(async (value) => {
        await this.updateSettings(
          () => {
            this.plugin.settings.outlineStyle = value;
          }
        );
      });
    });
  }
};

// src/types.ts
var DEFAULT_SETTINGS = {
  roundedRadius: 12,
  shadowStrength: "0 2px 8px",
  shadowColorLight: "#00000026",
  shadowColorDark: "#00000040",
  outlineWidth: 2,
  outlineColorLight: "#888888",
  outlineColorDark: "#aaaaaa",
  outlineStyle: "solid",
  enableGlass: true,
  enableGradient: true,
  enableCompact: true,
  enableHover: true,
  enableSticky: true,
  showSupportLinks: true
};

// src/main.ts
var CalloutMetadataPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.settings = {
      ...DEFAULT_SETTINGS
    };
    this.debouncedProcess = (0, import_obsidian2.debounce)(
      () => this.processAllViews(),
      200,
      true
    );
  }
  async onload() {
    await this.loadSettings();
    this.applyCSSVariables();
    this.applyEffectClasses();
    this.registerMarkdownPostProcessor(
      (el) => {
        processCallouts(el);
      }
    );
    this.app.workspace.onLayoutReady(
      () => {
        this.processAllViews();
        this.applyCSSVariables();
        this.applyEffectClasses();
        this.app.workspace.trigger(
          "css-change"
        );
      }
    );
    this.registerEvent(
      this.app.workspace.on(
        "layout-change",
        () => {
          this.debouncedProcess();
        }
      )
    );
    this.registerEvent(
      this.app.workspace.on(
        "css-change",
        () => {
          this.applyCSSVariables();
          this.applyEffectClasses();
        }
      )
    );
    this.addSettingTab(
      new CalloutMetadataSettingTab(
        this.app,
        this
      )
    );
  }
  /**
   * Get the correct document instance.
   *
   * Supports Obsidian popout windows.
   */
  getDocument() {
    return this.app.workspace.containerEl.ownerDocument;
  }
  /**
   * Apply CSS variables from settings.
   */
  applyCSSVariables() {
    const doc = this.getDocument();
    const root = doc.documentElement;
    const body = doc.body;
    const dark = body.classList.contains(
      "theme-dark"
    );
    root.style.setProperty(
      "--cm-rounded-radius",
      `${this.settings.roundedRadius}px`
    );
    root.style.setProperty(
      "--cm-shadow-strength",
      this.settings.shadowStrength
    );
    root.style.setProperty(
      "--cm-shadow-color",
      dark ? this.settings.shadowColorDark : this.settings.shadowColorLight
    );
    root.style.setProperty(
      "--cm-outline-width",
      `${this.settings.outlineWidth}px`
    );
    root.style.setProperty(
      "--cm-outline-color",
      dark ? this.settings.outlineColorDark : this.settings.outlineColorLight
    );
    body.classList.remove(
      "cm-outline-solid",
      "cm-outline-dashed",
      "cm-outline-dotted"
    );
    body.classList.add(
      `cm-outline-${this.settings.outlineStyle}`
    );
  }
  /**
   * Enable/disable optional effects
   * through body classes.
   */
  applyEffectClasses() {
    const doc = this.getDocument();
    const body = doc.body;
    const effects = {
      glass: this.settings.enableGlass,
      gradient: this.settings.enableGradient,
      compact: this.settings.enableCompact,
      hover: this.settings.enableHover,
      sticky: this.settings.enableSticky
    };
    Object.keys(effects).forEach(
      (name) => {
        body.toggleClass(
          `cm-${name}-disabled`,
          !effects[name]
        );
      }
    );
  }
  processAllViews() {
    this.app.workspace.iterateAllLeaves(
      (leaf) => {
        if (leaf.view instanceof import_obsidian2.MarkdownView) {
          processCallouts(
            leaf.view.containerEl
          );
        }
      }
    );
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      data
    );
  }
  async saveSettings() {
    await this.saveData(
      this.settings
    );
    this.applyCSSVariables();
    this.applyEffectClasses();
    this.app.workspace.trigger(
      "css-change"
    );
  }
};
